name: Build mumblelinktest

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cc -std=gnu99 -g -fsanitize=address mumble.c test.c -o mumblelinktest -Werror -Wall -Wpedantic -Wextra -Wconversion

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mumblelinktest-linux
          path: mumblelinktest

  build-linux-stub:
    name: Linux build (Stub)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cc -std=gnu99 -g -fsanitize=address mumble.c test.c -o mumblelinktest -Werror -Wall -Wpedantic -Wextra -Wconversion -DMUMBLE_STUB

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mumblelinktest-linux-stub
          path: mumblelinktest

  build-windows:
    name: Windows build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v3

      - name: Build
        run: cc -std=gnu99 mumble.c test.c -o mumblelinktest.exe -Werror -Wall -Wextra
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mumblelinktest-windows
          path: mumblelinktest.exe
